import Head from "next/head";
import About from "../components/About";
import Banner from "../components/Banner";
import Capabilities from "../components/Capabilities";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hire from "../components/Hire";
import Portfolio from "../components/Portfolio";
import Testimonials from "../components/Testimonials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Faizan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <Header />
        <Banner />
        <About />
        <Portfolio />
        <Capabilities />
        <Testimonials />
        <Hire />
        <Footer />
      </div>
    </>
  );
}
